package com.sample
import javax.swing.*;
import java.awt.*;

import com.sample.Drools.*;

 
rule "1.init"
	when
	then
		String question = "Classic or modern?";
		String[] answers = {"I need an escape from Tinder.", "I'm a modern girl."};
		int pane = JOptionPane.showOptionDialog(null, question, "Let's find a perfect romance movie for you. Answer the questions", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, answers, answers[0]);
		insert(new Question(question, answers[pane]));
end

rule "2.classic"
	when
		Question(question.equals("Classic or modern?"), answer.equals("I need an escape from Tinder."));
	then
		String question = "Black and white?";
		String[] answers = {"Definitely, love oldies!", "Let's go more modern."};
		int pane = JOptionPane.showOptionDialog(null, question, "Let's find a perfect romance movie for you. Answer the questions", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, answers, answers[0]);
		insert(new Question(question, answers[pane]));
end

rule "3.black"
	when
		Question(question.equals("Black and white?"), answer.equals("Definitely, love oldies!"));
	then
		String question = "A tale of friends or strangers?";
		String[] answers = {"Strangers.", "Friends."};
		int pane = JOptionPane.showOptionDialog(null, question, "Let's find a perfect romance movie for you. Answer the questions", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, answers, answers[0]);
		insert(new Question(question, answers[pane]));
end

rule "4.strangers"
	when
		Question(question.equals("Black and white?"), answer.equals("Strangers."));
	then
		String question = "Do they get together in the end";
		String[] answers = {"Please say yes!", "NBD."};
		int pane = JOptionPane.showOptionDialog(null, question, "Let's find a perfect romance movie for you. Answer the questions", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, answers, answers[0]);
		insert(new Question(question, answers[pane]));
end

rule "5.Please say yes"
	when
		Question(question.equals("Do they get together in the end"), answer.equals("Please say yes!"));
	then
		String question = "Perfect romance movie for you ";
		String answer = "Breakfast at Tiffany's";
		insert(new Question(question, answer));
end

rule "6.NBD."
	when
		Question(question.equals("Do they get together in the end"), answer.equals("NBD."));
	then
		String question = "Perfect romance movie for you ";
		String answer = "Roman Holiday";
		insert(new Question(question, answer));
end

rule "7.Friends"
	when
		Question(question.equals("A tale of friends or strangers?"), answer.equals("Friends."));
	then
		String question = "Perfect romance movie for you ";
		String answer = "Terms of Endearment";
		insert(new Question(question, answer));
end


rule "8.white"
	when
		Question(question.equals("Black and white?"), answer.equals("Let's go more modern."));
	then
		String question = "Based on a novel?";
		String[] answers = {"Not so much.", "I'm kind of a book worm."};
		int pane = JOptionPane.showOptionDialog(null, question, "Let's find a perfect romance movie for you. Answer the questions", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, answers, answers[0]);
		insert(new Question(question, answers[pane]));
end

rule "9.not so much"
	when
		Question(question.equals("Based on a novel?"), answer.equals("Not so much."));
	then
		String question = "Your thoughts on the 'gos?";
		String[] answers = {"Let's go earlier.", "Greatest years of my life."};
		int pane = JOptionPane.showOptionDialog(null, question, "Let's find a perfect romance movie for you. Answer the questions", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, answers, answers[0]);
		insert(new Question(question, answers[pane]));
end

rule "10.earlier"
	when
		Question(question.equals("Your thoughts on the 'gos?"), answer.equals("Let's go earlier."));
	then
		String question = "Ah, period piece it is. Biography?";
		String[] answers = {"Pass.", "Ok!"};
		int pane = JOptionPane.showOptionDialog(null, question, "Let's find a perfect romance movie for you. Answer the questions", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, answers, answers[0]);
		insert(new Question(question, answers[pane]));
end

rule "11.Pass"
	when
		Question(question.equals("Ah, period piece it is. Biography?"), answer.equals("Pass."));
	then
		String question = "Perfect romance movie for you ";
		String answer = "Shakespeare In Love";
		insert(new Question(question, answer));
end

rule "12.ok!"
	when
		Question(question.equals("Ah, period piece it is. Biography?"), answer.equals("Ok!"));
	then
		String question = "Art or film?";
		String[] answers = {"Art!", "Film!"};
		int pane = JOptionPane.showOptionDialog(null, question, "Let's find a perfect romance movie for you. Answer the questions", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, answers, answers[0]);
		insert(new Question(question, answers[pane]));
end

rule "13.Art"
	when
		Question(question.equals("Art or film?"), answer.equals("Art!"));
	then
		String question = "Perfect romance movie for you ";
		String answer = "Frida";
		insert(new Question(question, answer));
end

rule "14.Film"
	when
		Question(question.equals("Art or film?"), answer.equals("Film!"));
	then
		String question = "Perfect romance movie for you ";
		String answer = "Marilyn";
		insert(new Question(question, answer));
end

rule "15.greatest year of life"
	when
		Question(question.equals("Your thoughts on the 'gos?"), answer.equals("Greatest years of my life."));
	then
		String question = "Deep passion or innocent love?";
		String[] answers = {"Deep passion!", "Innocent love?"};
		int pane = JOptionPane.showOptionDialog(null, question, "Let's find a perfect romance movie for you. Answer the questions", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, answers, answers[0]);
		insert(new Question(question, answers[pane]));
end

rule "16.deep passion"
	when
		Question(question.equals("Deep passion or innocent love?"), answer.equals("Deep passion!"));
	then
		String question = "Do you like ghosts?";
		String[] answers = {"Bring it!", "No."};
		int pane = JOptionPane.showOptionDialog(null, question, "Let's find a perfect romance movie for you. Answer the questions", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, answers, answers[0]);
		insert(new Question(question, answers[pane]));
end

rule "17.Ghosts"
	when
		Question(question.equals("Do you like ghosts?"), answer.equals("Bring it!"));
	then
		String question = "Perfect romance movie for you ";
		String answer = "Ghost";
		insert(new Question(question, answer));
end

rule "18.No ghosts"
	when
		Question(question.equals("Do you like ghosts?"), answer.equals("No."));
	then
		String question = "Perfect romance movie for you ";
		String answer = "Jerry Maguire";
		insert(new Question(question, answer));
end

rule "19.deep passion"
	when
		Question(question.equals("Deep passion or innocent love?"), answer.equals("Innocent love?"));
	then
		String question = "Small town or big city?";
		String[] answers = {"Big city.", "Small town."};
		int pane = JOptionPane.showOptionDialog(null, question, "Let's find a perfect romance movie for you. Answer the questions", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, answers, answers[0]);
		insert(new Question(question, answers[pane]));
end

rule "20.Big city"
	when
		Question(question.equals("Small town or big city?"), answer.equals("Big city."));
	then
		String question = "Perfect romance movie for you ";
		String answer = "Clueless";
		insert(new Question(question, answer));
end

rule "21.Small town"
	when
		Question(question.equals("Small town or big city?"), answer.equals("Small town."));
	then
		String question = "A love that lasts decades?";
		String[] answers = {"Let's cut to the chase", "Love should last forever!"};
		int pane = JOptionPane.showOptionDialog(null, question, "Let's find a perfect romance movie for you. Answer the questions", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, answers, answers[0]);
		insert(new Question(question, answers[pane]));
end

rule "22. Cut to the chase"
	when
		Question(question.equals("A love that lasts decades?"), answer.equals("Let's cut to the chase"));
	then
		String question = "Perfect romance movie for you ";
		String answer = "What's Eating Gilbert Grape?";
		insert(new Question(question, answer));
end

rule "23. love forever"
	when
		Question(question.equals("A love that lasts decades?"), answer.equals("Love should last forever!"));
	then
		String question = "Perfect romance movie for you ";
		String answer = "Forrest Gump";
		insert(new Question(question, answer));
end

rule "24. based on novel"
	when
		Question(question.equals("Based on novel?"), answer.equals("I'm kind of a book worm."));
	then
		String question = "New or old?";
		String[] answers = {"New.", "Old."};
		int pane = JOptionPane.showOptionDialog(null, question, "Let's find a perfect romance movie for you. Answer the questions", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, answers, answers[0]);
		insert(new Question(question, answers[pane]));
end

rule "25.new"
	when
		Question(question.equals("New or old?"), answer.equals("New."));
	then
		String question = "Based in the U.S. or Mexico?";
		String[] answers = {"U.S.", "Viva Mexico!"};
		int pane = JOptionPane.showOptionDialog(null, question, "Let's find a perfect romance movie for you. Answer the questions", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, answers, answers[0]);
		insert(new Question(question, answers[pane]));
end

rule "26. U.S."
	when
		Question(question.equals("Based in the U.S. or Mexico?"), answer.equals("U.S."));
	then
		String question = "Perfect romance movie for you ";
		String answer = "The Great Gatsby (1974)";
		insert(new Question(question, answer));
end

rule "27. Mexico"
	when
		Question(question.equals("Based in the U.S. or Mexico?"), answer.equals("Viva Mexico!"));
	then
		String question = "Perfect romance movie for you ";
		String answer = "Like Water for Chocolate";
		insert(new Question(question, answer));
end

rule "28.old"
	when
		Question(question.equals("New or old?"), answer.equals("Old."));
	then
		String question = "Author Bronte or Austen?";
		String[] answers = {"I prefer Russian literature.", "Emily Bronte is my queen.", "Jane Austen all the way."};
		int pane = JOptionPane.showOptionDialog(null, question, "Let's find a perfect romance movie for you. Answer the questions", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, answers, answers[0]);
		insert(new Question(question, answers[pane]));
end

rule "29. russian"
	when
		Question(question.equals("Author Bronte or Austen?"), answer.equals("I prefer Russian literature."));
	then
		String question = "Perfect romance movie for you ";
		String answer = "Anna Kerenina";
		insert(new Question(question, answer));
end

rule "30.Bronte"
	when
		Question(question.equals("Author Bronte or Austen?"), answer.equals("Emily Bronte is my queen."));
	then
		String question = "Like love triangles?";
		String[] answers = {"I LOVE love triangles.", "Pass."};
		int pane = JOptionPane.showOptionDialog(null, question, "Let's find a perfect romance movie for you. Answer the questions", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, answers, answers[0]);
		insert(new Question(question, answers[pane]));
end

rule "31. Love Triangles"
	when
		Question(question.equals("Like love triangles?"), answer.equals("I LOVE love triangles."));
	then
		String question = "Perfect romance movie for you ";
		String answer = "Wuthering Heighs";
		insert(new Question(question, answer));
end

rule "32. no to Love Triangles"
	when
		Question(question.equals("Like love triangles?"), answer.equals("Pass."));
	then
		String question = "Perfect romance movie for you ";
		String answer = "Jane Eyre";
		insert(new Question(question, answer));
end

rule "33.Austen"
	when
		Question(question.equals("Author Bronte or Austen?"), answer.equals("Jane Austen all the way."));
	then
		String question = "Perfect romance movie for you ";
		String answer = "Mansfield Park";
		insert(new Question(question, answer));
end

rule "34.modern girl"
	when
		Question(question.equals("Classic or modern?"), answer.equals("I'm a modern girl."));
	then
		String question = "Comedy or drama?";
		String[] answers = {"I need a good laugh", "How about some action?", "Let's add some drama"};
		int pane = JOptionPane.showOptionDialog(null, question, "Let's find a perfect romance movie for you. Answer the questions", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, answers, answers[0]);
		insert(new Question(question, answers[pane]));
end

rule "35.good laugh"
	when
		Question(question.equals("Comedy or drama?"), answer.equals("I need a good laugh"));
	then
		String question = "Like adventures?";
		String[] answers = {"Preffer a different storyline.", "Who doesn't!?"};
		int pane = JOptionPane.showOptionDialog(null, question, "Let's find a perfect romance movie for you. Answer the questions", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, answers, answers[0]);
		insert(new Question(question, answers[pane]));
end

rule "36. not adventures"
	when
		Question(question.equals("Like adventures?"), answer.equals("Preffer a different storyline."));
	then
		String question = "Fish out of water?";
		String[] answers = {"Ooo... tell me more!", "Who doesn't!?"};
		int pane = JOptionPane.showOptionDialog(null, question, "Let's find a perfect romance movie for you. Answer the questions", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, answers, answers[0]);
		
		insert(new Question(question, answers[pane]));
end

rule "37. something more"
	when
		Question(question.equals("Fish out of water?"), answer.equals("Ooo... tell me more!"));
	then
		String question = "Take me to Queens!";
		String[] answers = {"Yes!!", "Huh?"};
		int pane = JOptionPane.showOptionDialog(null, question, "Let's find a perfect romance movie for you. Answer the questions", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, answers, answers[0]);
		
		insert(new Question(question, answers[pane]));
end

rule "38.Queens"
	when
		Question(question.equals("Take me to Queens!"), answer.equals("Yes!!"));
	then
		String question = "Perfect romance movie for you ";
		String answer = "Coming to America";
		insert(new Question(question, answer));
end

rule "39.not Queens"
	when
		Question(question.equals("Take me to Queens!"), answer.equals("Huh?"));
	then
		String question = "Perfect romance movie for you ";
		String answer = "Spanglish";
		insert(new Question(question, answer));
end

rule "40. No fish out of water"
	when
		Question(question.equals("Fish out of water?"), answer.equals("No."));
	then
		String question = "Pining for Christmas already?";
		String[] answers = {"Bring on the mistletoe!", "Not so much"};
		int pane = JOptionPane.showOptionDialog(null, question, "Let's find a perfect romance movie for you. Answer the questions", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, answers, answers[0]);
		
		insert(new Question(question, answers[pane]));
end

rule "41. Christmas"
	when
		Question(question.equals("Pining for Christmas already?"), answer.equals("Bring on the mistletoe!"));
	then
		String question = "Single and ready to mingle?";
		String[] answers = {"I prefer dating.", "Sure!"};
		int pane = JOptionPane.showOptionDialog(null, question, "Let's find a perfect romance movie for you. Answer the questions", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, answers, answers[0]);
		
		insert(new Question(question, answers[pane]));
end

rule "42.Dating"
	when
		Question(question.equals("Single and ready to mingle?"), answer.equals("I prefer dating."));
	then
		String question = "Groundhog Day theme?";
		String[] answers = {"Okey.", "No thanks."};
		int pane = JOptionPane.showOptionDialog(null, question, "Let's find a perfect romance movie for you. Answer the questions", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, answers, answers[0]);
		
		insert(new Question(question, answers[pane]));
end

rule "43.Groundhog theme"
	when
		Question(question.equals("Groundhog Day theme?"), answer.equals("Okey."));
	then
		String question = "Perfect romance movie for you ";
		String answer = "12 Dates of Christmas";
		insert(new Question(question, answer));
end

rule "44. No Groundhog theme"
	when
		Question(question.equals("Groundhog Day theme?"), answer.equals("No thanks."));
	then
		String question = "Perfect romance movie for you ";
		String answer = "Love Actually";
		insert(new Question(question, answer));
end

rule "45.single and ready to mingle"
	when
		Question(question.equals("Single and ready to mingle?"), answer.equals("Sure!"));
	then
		String question = "Perfect romance movie for you ";
		String answer = "Marry Me for Christmas";
		insert(new Question(question, answer));
end	

rule "46. not so much"
	when
		Question(question.equals("Pining for Christmas already?"), answer.equals("Not so much."));
	then
		String question = "Pick a Jennifer";
		String[] answers = {"Lopez!", "Garner!"};
		int pane = JOptionPane.showOptionDialog(null, question, "Let's find a perfect romance movie for you. Answer the questions", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, answers, answers[0]);
		
		insert(new Question(question, answers[pane]));
end

rule "47.Lopez"
	when
		Question(question.equals("Pick a Jennifer"), answer.equals("Lopez!"));
	then
		String question = "Perfect romance movie for you ";
		String answer = "Mald in Manhattan";
		insert(new Question(question, answer));
end	

rule "48.Garner"
	when
		Question(question.equals("Pick a Jennifer"), answer.equals("Garner!"));
	then
		String question = "Perfect romance movie for you ";
		String answer = "13 going on 30";
		insert(new Question(question, answer));
end	

rule "49.adventures"
	when
		Question(question.equals("Like adventures?"), answer.equals("Who doesn't!?"));
	then
		String question = "Perfect romance movie for you ";
		String answer = "Moonrise Kingdom";
		insert(new Question(question, answer));
end

rule "50.some action"
	when
		Question(question.equals("Comedy or drama?"), answer.equals("How about some action?"));
	then
		String question = "What kind of action?";
		String[] answers = {"A thrilling twist!", "Love a little risque!"};
		int pane = JOptionPane.showOptionDialog(null, question, "Let's find a perfect romance movie for you. Answer the questions", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, answers, answers[0]);
		insert(new Question(question, answers[pane]));
end

rule "51.thrilling twist"
	when
		Question(question.equals("What kind of action?"), answer.equals("A thrilling twist!"));
	then
		String question = "Perfect romance movie for you ";
		String answer = "Charlie Countryman";
		insert(new Question(question, answer));
end

rule "52.Risque"
	when
		Question(question.equals("What kind of action?"), answer.equals("Love a little risque!"));
	then
		String question = "One couple or multicuple?";
		String[] answers = {"One.", "The more, the merrier!"};
		int pane = JOptionPane.showOptionDialog(null, question, "Let's find a perfect romance movie for you. Answer the questions", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, answers, answers[0]);
		insert(new Question(question, answers[pane]));
end

rule "53.One couple"
	when
		Question(question.equals("One couple or multicuple?"), answer.equals("One."));
	then
		String question = "Perfect romance movie for you ";
		String answer = "Perfect Sense";
		insert(new Question(question, answer));
end

rule "54.more"
	when
		Question(question.equals("One couple or multicuple?"), answer.equals("The more, the merrier!"));
	then
		String question = "Perfect romance movie for you ";
		String answer = "The Little Death";
		insert(new Question(question, answer));
end

rule "55.drama"
	when
		Question(question.equals("Comedy or drama?"), answer.equals("Let's add some drama"));
	then
		String question = "Is your life at a crossroads?";
		String[] answers = {"My life is pretty stable.", "When is it not?"};
		int pane = JOptionPane.showOptionDialog(null, question, "Let's find a perfect romance movie for you. Answer the questions", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, answers, answers[0]);
		insert(new Question(question, answers[pane]));
end

rule "56.stable"
	when
		Question(question.equals("Is your life at a crossroads?"), answer.equals("My life is pretty stable."));
	then
		String question = "Are youe sure?";
		String[] answers = {"Yes!", "Ok, maybe not..."};
		int pane = JOptionPane.showOptionDialog(null, question, "Let's find a perfect romance movie for you. Answer the questions", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, answers, answers[0]);
		insert(new Question(question, answers[pane]));
end

rule "57.sure for stable"
	when
		Question(question.equals("Are youe sure?"), answer.equals("Yes!"));
	then
		String question = "You get one lifeline. Who do you call?";
		String[] answers = {"Fiends!", "Bros."};
		int pane = JOptionPane.showOptionDialog(null, question, "Let's find a perfect romance movie for you. Answer the questions", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, answers, answers[0]);
		insert(new Question(question, answers[pane]));
end

rule "58.Friends"
	when
		Question(question.equals("You get one lifeline. Who do you call?"), answer.equals("Friends!"));
	then
		String question = "Perfect romance movie for you ";
		String answer = "Life Partners";
		insert(new Question(question, answer));
end

rule "59.Bros"
	when
		Question(question.equals("You get one lifeline. Who do you call?"), answer.equals("Bros."));
	then
		String question = "Perfect romance movie for you ";
		String answer = "Someone Marry Barry";
		insert(new Question(question, answer));
end

rule "60.maybe not sure"
	when
		Question(question.equals("Are youe sure?"), answer.equals("Ok, maybe not..."));
	then
		String question = "Is family getting in the way?";
		String[] answers = {"When do they not?", "Just my relationships."};
		int pane = JOptionPane.showOptionDialog(null, question, "Let's find a perfect romance movie for you. Answer the questions", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, answers, answers[0]);
		insert(new Question(question, answers[pane]));
end

rule "61.family in the way"
	when
		Question(question.equals("Is family getting in the way?"), answer.equals("When do they not?"));
	then
		String question = "A story of sibling?";
		String[] answers = {"Yes.", "Parents are crazy too!"};
		int pane = JOptionPane.showOptionDialog(null, question, "Let's find a perfect romance movie for you. Answer the questions", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, answers, answers[0]);
		insert(new Question(question, answers[pane]));
end

rule "62.siblings"
	when
		Question(question.equals("A story of sibling?"), answer.equals("Yes."));
	then
		String question = "Brother or sister?";
		String[] answers = {"Brother.", "Sister."};
		int pane = JOptionPane.showOptionDialog(null, question, "Let's find a perfect romance movie for you. Answer the questions", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, answers, answers[0]);
		insert(new Question(question, answers[pane]));
end

rule "63.Brother"
	when
		Question(question.equals("Brother or sister?"), answer.equals("Brother."));
	then
		String question = "Perfect romance movie for you ";
		String answer = "Benny and Joon";
		insert(new Question(question, answer));
end

rule "64.Sister"
	when
		Question(question.equals("Brother or sister?"), answer.equals("Sister."));
	then
		String question = "Someone getting married?";
		String[] answers = {"No way!", "I love weddings!"};
		int pane = JOptionPane.showOptionDialog(null, question, "Let's find a perfect romance movie for you. Answer the questions", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, answers, answers[0]);
		insert(new Question(question, answers[pane]));
end

rule "65. no married"
	when
		Question(question.equals("Someone getting married?"), answer.equals("No way!"));
	then
		String question = "Perfect romance movie for you ";
		String answer = "Your Sister's Sister";
		insert(new Question(question, answer));
end

rule "66.marriage"
	when
		Question(question.equals("Someone getting married?"), answer.equals("I love weddings!"));
	then
		String question = "Perfect romance movie for you ";
		String answer = "Save the Date";
		insert(new Question(question, answer));
end

rule "67.parents"
	when
		Question(question.equals("A story of sibling?"), answer.equals("Parents are crazy too!"));
	then
		String question = "Your parents?";
		String[] answers = {"Oh yeah.", "In-laws."};
		int pane = JOptionPane.showOptionDialog(null, question, "Let's find a perfect romance movie for you. Answer the questions", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, answers, answers[0]);
		insert(new Question(question, answers[pane]));
end

rule "68.my parents"
	when
		Question(question.equals("Your parents?"), answer.equals("Oh yeah."));
	then
		String question = "Perfect romance movie for you ";
		String answer = "The Beginners";
		insert(new Question(question, answer));
end

rule "69.in-law"
	when
		Question(question.equals("Your parents?"), answer.equals("In-laws."));
	then
		String question = "Perfect romance movie for you ";
		String answer = "While You Were Sleeping";
		insert(new Question(question, answer));
end

rule "70.family in relationships"
	when
		Question(question.equals("Is family getting in the way?"), answer.equals("Just my relationships."));
	then
		String question = "Do they usually work out?";
		String[] answers = {"Always!", "I can handle a break-up."};
		int pane = JOptionPane.showOptionDialog(null, question, "Let's find a perfect romance movie for you. Answer the questions", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, answers, answers[0]);
		insert(new Question(question, answers[pane]));
end

rule "71.work out"
	when
		Question(question.equals("Do they usually work out?"), answer.equals("Always!"));
	then
		String question = "Perfect romance movie for you ";
		String answer = "Silver Linings Playbook";
		insert(new Question(question, answer));
end

rule "72.handle break-up"
	when
		Question(question.equals("Do they usually work out?"), answer.equals("I can handle a break-up."));
	then
		String question = "Perfect romance movie for you ";
		String answer = "Someone Like You";
		insert(new Question(question, answer));
end

rule "73.not stable"
	when
		Question(question.equals("Is your life at a crossroads?"), answer.equals("When is it not?"));
	then
		String question = "Like Sci-Fi?";
		String[] answers = {"Sure!", "Nope."};
		int pane = JOptionPane.showOptionDialog(null, question, "Let's find a perfect romance movie for you. Answer the questions", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, answers, answers[0]);
		insert(new Question(question, answers[pane]));
end

rule "74.sci-fi"
	when
		Question(question.equals("Like Sci-Fi?"), answer.equals("Sure!"));
	then
		String question = "Present or alternate universe?";
		String[] answers = {"Present.", "Let's get outta here!"};
		int pane = JOptionPane.showOptionDialog(null, question, "Let's find a perfect romance movie for you. Answer the questions", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, answers, answers[0]);
		insert(new Question(question, answers[pane]));
end

rule "75.present"
	when
		Question(question.equals("Present or alternate universe?"), answer.equals("Present."));
	then
		String question = "Is the world ending?";
		String[] answers = {"Not yet!", "Might as well be."};
		int pane = JOptionPane.showOptionDialog(null, question, "Let's find a perfect romance movie for you. Answer the questions", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, answers, answers[0]);
		insert(new Question(question, answers[pane]));
end

rule "76. no world-ending"
	when
		Question(question.equals("Is the world ending?"), answer.equals("Not yet!"));
	then
		String question = "Fan of Duplass Brothers?";
		String[] answers = {"Love them!", "Who?"};
		int pane = JOptionPane.showOptionDialog(null, question, "Let's find a perfect romance movie for you. Answer the questions", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, answers, answers[0]);
		insert(new Question(question, answers[pane]));
end

rule "77.Duplass"
	when
		Question(question.equals("Fan of Duplass Brothers?"), answer.equals("Love them!"));
	then
		String question = "Perfect romance movie for you ";
		String answer = "The One I Love";
		insert(new Question(question, answer));
end

rule "78.not Duplass"
	when
		Question(question.equals("Fan of Duplass Brothers?"), answer.equals("Who?"));
	then
		String question = "Perfect romance movie for you ";
		String answer = "In Your Eyes";
		insert(new Question(question, answer));
end

rule "79.true world-ending"
	when
		Question(question.equals("Is the world ending?"), answer.equals("Might as ell be."));
	then
		String question = "Perfect romance movie for you ";
		String answer = "Seeking a Friend for the End of the World";
		insert(new Question(question, answer));
end

rule "80.alternate"
	when
		Question(question.equals("Present or alternate universe?"), answer.equals("Let's get outta here!"));
	then
		String question = "Fan of Christmas?";
		String[] answers = {"Nah.", "Sure!"};
		int pane = JOptionPane.showOptionDialog(null, question, "Let's find a perfect romance movie for you. Answer the questions", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, answers, answers[0]);
		insert(new Question(question, answers[pane]));
	end
	
rule "81.not fan of christmas"
	when
		Question(question.equals("Fan of Christmas?"), answer.equals("Nah."));
	then
		String question = "Perfect romance movie for you ";
		String answer = "Mr. Nobody";
		insert(new Question(question, answer));
end	

rule "94.fan of christmas"
	when
		Question(question.equals("Fan of Christmas?"), answer.equals("Sure!"));
	then
		String question = "Perfect romance movie for you ";
		String answer = "Holidaze";
		insert(new Question(question, answer));
end	

rule "95.no sci-fi"
	when
		Question(question.equals("Like Sci-Fi?"), answer.equals("Nope."));
	then
		String question = "Want to relive college?";
		String[] answers = {"I'd rather not.", "Take me back!"};
		int pane = JOptionPane.showOptionDialog(null, question, "Let's find a perfect romance movie for you. Answer the questions", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, answers, answers[0]);
		insert(new Question(question, answers[pane]));
end

rule "82. not back to collage"
	when
		Question(question.equals("Want to relive college?"), answer.equals("I'd rather not."));
	then
		String question = "Fan of young love?";
		String[] answers = {"I'm interested!", "Prefer older."};
		int pane = JOptionPane.showOptionDialog(null, question, "Let's find a perfect romance movie for you. Answer the questions", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, answers, answers[0]);
		insert(new Question(question, answers[pane]));
end

rule "83. young love"
	when
		Question(question.equals("Fan of young love?"), answer.equals("I'm interested!"));
	then
		String question = "Had a date for prom?";
		String[] answers = {"Oh yeah!", "I'd rather forget."};
		int pane = JOptionPane.showOptionDialog(null, question, "Let's find a perfect romance movie for you. Answer the questions", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, answers, answers[0]);
		insert(new Question(question, answers[pane]));
end

rule "84.date for prom"
	when
		Question(question.equals("Had a date for prom?"), answer.equals("Oh yeah!"));
	then
		String question = "Perfect romance movie for you ";
		String answer = "Drive Me Crazy";
		insert(new Question(question, answer));
end	

rule "85. not date for prom"
	when
		Question(question.equals("Had a date for prom?"), answer.equals("I'd rather forget."));
	then
		String question = "Had a high school sweetheart?";
		String[] answers = {"High school was full of angst.", "It was the best kind of love story."};
		int pane = JOptionPane.showOptionDialog(null, question, "Let's find a perfect romance movie for you. Answer the questions", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, answers, answers[0]);
		insert(new Question(question, answers[pane]));
end

rule "86.high school full of angst"
	when
		Question(question.equals("Had a high school sweetheart?"), answer.equals("High school was full of angst."));
	then
		String question = "Perfect romance movie for you ";
		String answer = "6 Years";
		insert(new Question(question, answer));
end	

rule "87.high school - the best love"
	when
		Question(question.equals("Had a high school sweetheart?"), answer.equals("It was the best kind of love story."));
	then
		String question = "Perfect romance movie for you ";
		String answer = "Can't Hardly Wait";
		insert(new Question(question, answer));
end	

rule "88. not young love"
	when
		Question(question.equals("Fan of young love?"), answer.equals("Prefer older."));
	then
		String question = "Rich or middle class?";
		String[] answers = {"Show me the Benjamins.", "Partial to the average Joe."};
		int pane = JOptionPane.showOptionDialog(null, question, "Let's find a perfect romance movie for you. Answer the questions", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, answers, answers[0]);
		insert(new Question(question, answers[pane]));
end

rule "89.Benjamins"
	when
		Question(question.equals("Rich or middle class?"), answer.equals("Show me the Benjamins."));
	then
		String question = "Fan of ballroom dancing?";
		String[] answers = {"I've got moves.", "I have two left feet."};
		int pane = JOptionPane.showOptionDialog(null, question, "Let's find a perfect romance movie for you. Answer the questions", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, answers, answers[0]);
		insert(new Question(question, answers[pane]));
end

rule "90. got moves"
	when
		Question(question.equals("Fan of ballroom dancing?"), answer.equals("I've got moves."));
	then
		String question = "Perfect romance movie for you ";
		String answer = "And So It Goes";
		insert(new Question(question, answer));
end

rule "91. two left feet"
	when
		Question(question.equals("Fan of ballroom dancing?"), answer.equals("I have two left feet."));
	then
		String question = "Perfect romance movie for you ";
		String answer = "Shall We Dance?";
		insert(new Question(question, answer));
end

rule "92.Joe"
	when
		Question(question.equals("Rich or middle class?"), answer.equals("Partial to the average Joe."));
	then
		String question = "Hoping for love after a break-up?";
		String[] answers = {"Yes! We all need hope!", "Less heartache."};
		int pane = JOptionPane.showOptionDialog(null, question, "Let's find a perfect romance movie for you. Answer the questions", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, answers, answers[0]);
		insert(new Question(question, answers[pane]));
end

rule "93. Hope"
	when
		Question(question.equals("Hoping for love after a break-up?"), answer.equals("Yes! We all need hope!"));
	then
		String question = "Perfect romance movie for you ";
		String answer = "Crazy Kind Of Love";
		insert(new Question(question, answer));
end

rule "94. Hopeless"
	when
		Question(question.equals("Hoping for love after a break-up?"), answer.equals("Less heartache."));
	then
		String question = "Perfect romance movie for you ";
		String answer = "Elsa & Fred";
		insert(new Question(question, answer));
end

rule "95.back to collage"
	when
		Question(question.equals("Want to relive college?"), answer.equals("Take me back!"));
	then
		String question = "Happy endings or college drama?";
		String[] answers = {"Happy endings!", "Drama."};
		int pane = JOptionPane.showOptionDialog(null, question, "Let's find a perfect romance movie for you. Answer the questions", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, answers, answers[0]);
		insert(new Question(question, answers[pane]));
end

rule "96. Happy endings"
	when
		Question(question.equals("Happy endings or college drama?"), answer.equals("Happy endings!"));
	then
		String question = "Perfect romance movie for you ";
		String answer = "Liberal Arts";
		insert(new Question(question, answer));
end

rule "97. prefer drama"
	when
		Question(question.equals("Happy endings or college drama?"), answer.equals("Drama."));
	then
		String question = "Perfect romance movie for you ";
		String answer = "The Graduate";
		insert(new Question(question, answer));
end

rule "98.final"
	when
		q : Question(question.equals("Perfect romance movie for you "));
	then
		JOptionPane.showMessageDialog(null, q.answer, q.question, JOptionPane.INFORMATION_MESSAGE);
end




